apiVersion: container.gcp.upbound.io/v1beta2
kind: Cluster
metadata:
  name: crossplane-dev-gke
spec:
  forProvider:
    location: us-east1

    networkRef:
      name: crossplane-vpc

    subnetworkRef:
      name: crossplane-subnet-us-east1

    removeDefaultNodePool: true
    initialNodeCount: 1

    networkingMode: VPC_NATIVE

    ipAllocationPolicy:
      - clusterSecondaryRangeNameRef:
          name: pods-range
        servicesSecondaryRangeNameRef:
          name: services-range

  providerConfigRef:
    name: default