apiVersion: sql.gcp.upbound.io/v1beta2
kind: DatabaseInstance
metadata:
  name: crossplane-postgres
spec:
  forProvider:
    region: us-east1
    databaseVersion: POSTGRES_15
    deletionProtection: false

    settings:
      tier: db-f1-micro
      diskSize: 20
      diskType: PD_SSD

      ipConfiguration:
        ipv4Enabled: false
        privateNetworkRef:
          name: crossplane-vpc

  providerConfigRef:
    name: default