apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dev-db-password
  namespace: default

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore

  target:
    name: dev-db-password
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: password
      remoteRef:
        key: dev-db-password
        version: latest